### ISSUE TITLE
Unable to Debug/Attach after upgrade to VS Pro 16.7.2

### ISSUE THREAD

**Issue by ElRapoh** [GordianDotNet/VSMonoDebugger#22]
After Visual Studio Upgrade 2019 from 16.4.4 to 16.7.2 there's no way to run VSMnonoDebugger. Everything worked on 
Removing and reinstalling VSMnonoDebugger doesn't help.

![Cattura](https://user-images.githubusercontent.com/4816803/91690632-952a7280-eb66-11ea-97f7-aec60ed722b5.PNG)

I tried to download VSMnonoDebugger and start debugging. Here is the exception:

Message:
Method not found: 'Void Mono.Debugging.Evaluation.ObjectValueAdaptor.set_DebuggerSession(Mono.Debugging.Client.DebuggerSession)'.

Source: Mono.Debugging.Soft

Stack trace:
   at Mono.Debugging.Soft.SoftDebuggerSession..ctor()
   at Mono.Debugging.VisualStudio.XamarinEngine.SerializeDebuggerOptions(String jsonDebugOptions) in C:\[...]\VSMonoDebugger-master\VSMonoDebugger\Mono.Debugging.VisualStudio\XamarinEngine.cs:line 41

**Comment by ElRapoh** [comment]
Issue was resolved on this fork: https://github.com/ElRapoh/VSMonoDebugger

Al possible NuGet packaged have been upgraded and the local copy of some libraries has been disabled.

Most problems seem to be related to Xamarin. Maybe the right way to resolve them would be adding Xamarin as a prerequisite for VSMonoDebugger and make use Mono debugging libraries provided by VS instead of adding them to the package.

**Comment by BDisp** [comment]
Why don't you submit a PR?

**Comment by ElRapoh** [comment]
I made my changes at work only for our development purposes (we need extensively to debug mono on Linux from VS), no extensive tests were done on different VS versions and behaviours.

I just gave to the code some kicks to make him work on our workstations.

Better if someone who actively mantains the code verifies what I've done and then eventually makes a decent commit on the production trunk.

**Comment by GordianDotNet** [comment]
Can you use the new VSMonoDebugger2022 with Visual Studio 2022?
