### ISSUE TITLE
Unable to convert mdb file

### ISSUE THREAD

**Issue by dxball** [GordianDotNet/VSMonoDebugger#36]
Windows 10 21H2
Visual Studio 2022 Version 17.6.5
VSMonoDebugger2022 Version 2.2209.1806

Select `Build Startup Project with MDB files`

Get this error message 
```
2023-07-21 11:35:09.4718|INFO|VSMonoDebugger.MonoVisualStudioExtension|<project> - OutputDir: <output dir>
2023-07-21 11:35:09.4718|ERROR|VSMonoDebugger.MonoVisualStudioExtension|Catched: ConvertPdb2MdbAsync - MonoVisualStudioExtension.cs(772)|System.IO.FileNotFoundException: Could not load file or assembly 'Mono.Cecil, Version=0.10.0.0, Culture=neutral, PublicKeyToken=50cebf1cceb9d05e' or one of its dependencies. System could not found the file.
File name: 'Mono.Cecil, Version=0.10.0.0, Culture=neutral, PublicKeyToken=50cebf1cceb9d05e'
   at Pdb2Mdb.Converter.Convert(String filename)
   at VSMonoDebugger.MonoVisualStudioExtension.<>c__DisplayClass32_0.<ConvertPdb2MdbAsync>b__0()
```

I check the extension folder at `%LocalAppData%\Microsoft\VisualStudio\17.0_847708e2\Extensions\gmvzud4n.g5l`
found the version of `Mono.Cecil.dll` is `0.11.4.0`, not `0.10.0.0`

**Comment by wilstark** [comment]
Yeah, you need VS 2022 17.3.4 as Cecil 11.4 removed a few types compared to 10.0 that pdb2mdb needs. Looks like at this point, MS has pulled 17.3.4 in favor of later versions (17.8+). So, yikes. VSMonoDebugger is currently out of commission.

**Comment by wilstark** [comment]
Looks like 17.3.4 is available (still) here: https://learn.microsoft.com/en-us/visualstudio/releases/2022/release-history#release-dates-and-build-numbers

**Comment by ShockWave2048** [comment]
> [wilstark](/wilstark)

But i can install only Cecil 0.10.0.0. Why a still get this error? Cecil DLL (0.10.0.0) exists in Debug folder.
