### ISSUE TITLE
Unable to debug

### ISSUE THREAD

**Issue by monoluser** [GordianDotNet/VSMonoDebugger#8]
Hi!

Thank you so much for your effort of developing a Mono remote debugger!
I'm having the following (maybe small?) issue:
```
2019-03-12 10:55:53.3776|INFO|VSMonoDebugger.Services.NLogService|===== DeployAndRunCommandOverSSH =====
2019-03-12 10:55:53.3776|TRACE|VSMonoDebugger.Services.NLogService|Entering: StartDebuggerAsync - SSHDebugger.cs(35)
2019-03-12 10:55:53.3776|INFO|VSMonoDebugger.Services.NLogService|StartDebuggerAsync - debug
2019-03-12 10:55:55.3558|INFO|VSMonoDebugger.Services.NLogService|Run PreDebugScript: echo
2019-03-12 10:55:55.3558|INFO|VSMonoDebugger.Services.NLogService|Run DebugScript: /usr/local/bin/mono --debugger-agent=address=0.0.0.0:11000,transport=dt_socket,server=y --debug=mdb-optimizations RemoteBugging.exe  &
2019-03-12 10:55:55.3708|TRACE|VSMonoDebugger.Services.NLogService|Entering: SetRegistryRoot - XamarinEngine.cs(220)
2019-03-12 10:55:55.3708|TRACE|VSMonoDebugger.Services.NLogService|Entering: SetLocale - XamarinEngine.cs(214)
2019-03-12 10:55:55.3728|TRACE|VSMonoDebugger.Services.NLogService|Entering: LaunchSuspended - XamarinEngine.cs(112)
2019-03-12 10:55:55.3728|TRACE|VSMonoDebugger.Services.NLogService|Entering: SerializeDebuggerOptions - XamarinEngine.cs(34)
2019-03-12 10:55:55.3728|ERROR|VSMonoDebugger.Services.NLogService|System.TypeInitializationException: The type initializer for 'Clide.Patterns.Adapter.Adapters' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Diagnostics.Tracer, Version=2.0.0.0, Culture=neutral, PublicKeyToken=173d89ffae9ce988' or one of its dependencies. The system cannot find the file specified.
   at Clide.DevEnvFactory.InitializeContainer(IServiceProvider services)
   at Clide.DevEnvFactory.<Get>b__0(IServiceProvider s)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Clide.DevEnvFactory.Get(IServiceProvider services)
   at Clide.DevEnv.Get(IServiceProvider serviceProvider)
   at Clide.ServiceLocator.<.cctor>b__0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at Clide.ServiceLocator.get_GlobalLocator()
   at Clide.Patterns.Adapter.Adapters..cctor()
   --- End of inner exception stack trace ---
   at Clide.Patterns.Adapter.Adapters.get_ServiceInstance()
   at EnvDTE.AdapterFacade.Adapt(Project project)
   at Mono.Debugging.VisualStudio.StartInfo.GetUserAssemblyNamesAndMaps()
   at Mono.Debugging.VisualStudio.StartInfo..ctor(SoftDebuggerStartArgs start_args, DebuggingOptions options, Project startupProject)
   at Mono.Debugging.VisualStudio.XamarinEngine.SerializeDebuggerOptions(String jsonDebugOptions) in C:\source\VSMonoDebugger\VSMonoDebugger\Mono.Debugging.VisualStudio\XamarinEngine.cs:line 75
2019-03-12 10:55:55.3728|ERROR|VSMonoDebugger.MonoVisualStudioExtension|System.Runtime.InteropServices.COMException (0x89710016): Unable to start program 'C:\temp\dotnets\RemoteBugging\bin\Debug\net461\RemoteBugging.exe'.

Uncaught exception during type initialization.
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
   at VSMonoDebugger.MonoVisualStudioExtension.AttachDebuggerToRunningProcess(DebugOptions debugOptions) in C:\source\VSMonoDebugger\VSMonoDebugger\Services\MonoVisualStudioExtension.cs:line 247
2019-03-12 10:55:55.3728|ERROR|VSMonoDebugger.Services.NLogService|System.Runtime.InteropServices.COMException (0x89710016): Unable to start program 'C:\temp\dotnets\RemoteBugging\bin\Debug\net461\RemoteBugging.exe'.

Uncaught exception during type initialization.
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
   at VSMonoDebugger.MonoVisualStudioExtension.AttachDebuggerToRunningProcess(DebugOptions debugOptions) in C:\source\VSMonoDebugger\VSMonoDebugger\Services\MonoVisualStudioExtension.cs:line 260
   at VSMonoDebugger.VSMonoDebuggerCommands.<DeployAndRunCommandOverSSH>d__25.MoveNext() in C:\source\VSMonoDebugger\VSMonoDebugger\VSMonoDebuggerCommands.Implementation.cs:line 143
```
Can you figure it out? Do you need more input?

Thanks for your help!

**Comment by GordianDotNet** [comment]
Thanks for reporting! I had the same error after reinstalling Windows 10 and installing Visual Studio 2019 only. I fixed the bug in version 0.8.0.

DLL System.Diagnostics.Tracer, Version=2.0.0.0 was missing.
